name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'Xano Development Methodology.md'
    workflow_dispatch: # This allows manual triggering

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic
      
      - name: Convert Markdown to PDF
        run: |
          pandoc "Xano Development Methodology.md" -o "Xano Development Methodology.pdf" --pdf-engine=xelatex
      
      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "Xano Development Methodology.pdf"
          git commit -m "Convert markdown to PDF" || echo "No changes to commit"
          git push