name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'Xano Development Methodology.md'  # Replace with the path to your specific markdown file

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install md-to-pdf
        run: npm install -g md-to-pdf
      
      - name: Convert Markdown to PDF
        run: |
          md-to-pdf "Xano Development Methodology.md"  # Replace with your markdown file path
      
      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "Xano Development Methodology.pdf"   # Replace with the path where the PDF is generated
          git commit -m "Convert markdown to PDF" || echo "No changes to commit"
          git push