name: Convert Xano Methodology to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'Xano Development Methodology.md'

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Just fetch the latest commit to speed things up

      - name: Check if Xano methodology file changed
        id: changed_files
        run: |
          # Check if file exists first
          if [ -f "Xano Development Methodology.md" ]; then
            echo "file=Xano Development Methodology.md" >> $GITHUB_OUTPUT
            echo "files=[\"Xano Development Methodology.md\"]" >> $GITHUB_OUTPUT
            echo "Xano Development Methodology file exists, proceeding with conversion"
          else
            echo "Xano Development Methodology file does not exist"
            echo "files=[]" >> $GITHUB_OUTPUT
            exit 0
          fi
      
      - name: Setup Pandoc
        if: steps.changed_files.outputs.files != '[]'
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install minimal requirements for PDF generation
        if: steps.changed_files.outputs.files != '[]'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends texlive-xetex texlive-fonts-recommended texlive-plain-generic texlive-latex-base texlive-latex-recommended lmodern

      - name: Create custom styles
        if: steps.changed_files.outputs.files != '[]'
        run: |
          cat > custom.css << 'EOL'
          body {
            font-family: "DejaVu Sans", Arial, Helvetica, sans-serif;
            line-height: 1.5;
            max-width: 900px;
            margin: 0 auto;
            padding: 2em;
            color: #333;
          }
          h1, h2, h3, h4, h5, h6 {
            color: #2c3e50;
            margin-top: 1.5em;
            margin-bottom: 0.5em;
          }
          h1 { font-size: 2.2em; }
          h2 { font-size: 1.8em; }
          h3 { font-size: 1.5em; }
          a { color: #3498db; }
          code {
            background-color: #f7f7f7;
            padding: 0.2em 0.4em;
            border-radius: 3px;
            font-family: "DejaVu Sans Mono", monospace;
          }
          pre {
            background-color: #f7f7f7;
            padding: 1em;
            border-radius: 5px;
            overflow-x: auto;
          }
          blockquote {
            border-left: 4px solid #e7e7e7;
            padding-left: 1em;
            margin-left: 0;
            color: #666;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin: 1em 0;
          }
          table, th, td {
            border: 1px solid #ddd;
          }
          th, td {
            padding: 0.5em;
            text-align: left;
          }
          th {
            background-color: #f2f2f2;
          }
          img {
            max-width: 100%;
            height: auto;
          }
          EOL

      - name: Convert Xano methodology to PDF
        if: steps.changed_files.outputs.files != '[]'
        run: |
          FILE="Xano Development Methodology.md"
          OUTPUT_PDF="${FILE%.md}.pdf"
          
          # Skip if file doesn't exist
          if [ ! -f "$FILE" ]; then
            echo "File $FILE no longer exists, skipping"
            exit 0
          fi
          
          echo "Converting $FILE to PDF using Pandoc"
          pandoc "$FILE" \
            -f markdown \
            -t pdf \
            -o "$OUTPUT_PDF" \
            --pdf-engine=xelatex \
            --toc \
            --variable=colorlinks=true \
            --variable=linkcolor=blue \
            --variable=geometry:margin=1in \
            --variable=mainfont="DejaVu Serif" \
            --css=custom.css

      - name: Create Pull Request
        if: steps.changed_files.outputs.files != '[]'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Convert markdown to PDF"
          title: "Convert Markdown to PDF"
          body: "Automatically generated PDF from markdown file"
          branch: pdf-generation
          base: main