name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'Xano Development Methodology.md'
  workflow_dispatch: # This allows manual triggering

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic texlive-latex-extra
      
      - name: Create custom styles
        run: |
          cat > custom.css << 'EOL'
          body {
            font-family: "DejaVu Sans", Arial, Helvetica, sans-serif;
            line-height: 1.5;
            max-width: 900px;
            margin: 0 auto;
            padding: 2em;
            color: #333;
          }
          h1, h2, h3, h4, h5, h6 {
            color: #2c3e50;
            margin-top: 1.5em;
            margin-bottom: 0.5em;
          }
          h1 { font-size: 2.2em; }
          h2 { font-size: 1.8em; }
          h3 { font-size: 1.5em; }
          a { color: #3498db; }
          code {
            background-color: #f7f7f7;
            padding: 0.2em 0.4em;
            border-radius: 3px;
            font-family: "DejaVu Sans Mono", monospace;
          }
          pre {
            background-color: #f7f7f7;
            padding: 1em;
            border-radius: 5px;
            overflow-x: auto;
          }
          blockquote {
            border-left: 4px solid #e7e7e7;
            padding-left: 1em;
            margin-left: 0;
            color: #666;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin: 1em 0;
          }
          table, th, td {
            border: 1px solid #ddd;
          }
          th, td {
            padding: 0.5em;
            text-align: left;
          }
          th {
            background-color: #f2f2f2;
          }
          img {
            max-width: 100%;
            height: auto;
          }
          EOL
      
      - name: Convert Markdown to PDF
        run: |
          pandoc "Xano Development Methodology.md" \
            -o "Xano Development Methodology.pdf" \
            --pdf-engine=xelatex \
            --toc \
            --toc-depth=3 \
            --highlight-style=tango \
            --variable=colorlinks \
            --variable=urlcolor=blue \
            --variable=toccolor=blue \
            --variable=geometry:margin=1in \
            --variable=mainfont="DejaVu Serif" \
            --variable=sansfont="DejaVu Sans" \
            --variable=monofont="DejaVu Sans Mono" \
            --variable=fontsize=11pt \
            --css=custom.css
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Convert markdown to PDF"
          title: "Convert Markdown to PDF"
          body: "Automatically generated PDF from markdown file"
          branch: pdf-generation
          base: main