name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'Xano Development Methodology.md'

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic
      
      - name: Convert Markdown to PDF
        run: |
          pandoc "Xano Development Methodology.md" -o "Xano Development Methodology.pdf" --pdf-engine=xelatex
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Convert markdown to PDF"
          title: "Convert Markdown to PDF"
          body: "Automatically generated PDF from markdown file"
          branch: pdf-generation
          base: main